from pump_end_v2.gate.feature_view import (
    GATE_CATEGORICAL_FEATURE_COLUMNS,
    GATE_FEATURE_COLUMNS,
    GATE_IDENTITY_COLUMNS,
    GATE_NUMERIC_FEATURE_COLUMNS,
)

DETECTOR_IDENTITY_COLUMNS: tuple[str, ...] = (
    "decision_row_id",
    "episode_id",
    "symbol",
    "context_bar_open_time",
    "decision_time",
    "entry_bar_open_time",
)

DETECTOR_FEATURE_COLUMNS: tuple[str, ...] = (
    "close_ret_1",
    "close_ret_4",
    "close_ret_12",
    "intrabar_range_pct",
    "candle_body_pct",
    "upper_wick_pct",
    "lower_wick_pct",
    "rolling_volatility_4",
    "rolling_volatility_12",
    "rsi_like_14",
    "mfi_like_14",
    "macd_line",
    "macd_hist",
    "heat_flag",
    "fade_flag",
    "dollar_volume",
    "dollar_volume_ratio_12",
    "liquidity_score_12",
    "runup_pct_at_context",
    "volume_ratio_at_context",
    "pump_context_flag",
    "distance_from_episode_high_pct",
    "episode_age_bars",
    "episode_runup_from_open_pct",
    "episode_extension_from_open_pct",
    "bars_since_episode_high",
    "drawdown_from_episode_high_so_far",
    "high_retest_count",
    "high_persistence_4",
    "episode_pump_context_streak",
    "btc_close_ret_1",
    "btc_close_ret_4",
    "btc_close_ret_12",
    "btc_intrabar_range_pct",
    "btc_volume_ratio",
    "btc_pump_context_flag",
    "eth_close_ret_1",
    "eth_close_ret_4",
    "eth_close_ret_12",
    "eth_intrabar_range_pct",
    "eth_volume_ratio",
    "eth_pump_context_flag",
    "breadth_universe_size",
    "breadth_advancers_share",
    "breadth_mean_close_ret_1",
    "breadth_median_close_ret_1",
    "breadth_std_close_ret_1",
    "breadth_near_high_share",
    "breadth_pump_context_share",
    "breadth_volume_spike_share",
)

DETECTOR_SEQUENCE_FEATURE_COLUMNS: tuple[str, ...] = (
    "eth_close_ret_12",
    "liquidity_score_12",
    "btc_close_ret_12",
    "macd_hist",
    "btc_intrabar_range_pct",
    "rolling_volatility_12",
    "eth_close_ret_4",
    "macd_line",
    "btc_close_ret_4",
    "dollar_volume",
    "mfi_like_14",
    "episode_extension_from_open_pct",
    "close_ret_4",
    "eth_intrabar_range_pct",
    "rsi_like_14",
    "rolling_volatility_4",
)

BLOCKED_COLUMNS: tuple[str, ...] = (
    "episode_close_time",
    "duration_bars",
    "expiry_reason",
    "future_prepullback_squeeze_pct",
    "future_pullback_pct",
    "future_net_edge_pct",
    "bars_to_pullback",
    "bars_to_peak_after_row",
    "bars_to_resolution",
    "future_outcome_class",
    "signal_quality_h32",
    "target_good_short_now",
    "target_reason",
    "entry_quality_score",
    "ideal_entry_row_id",
    "ideal_entry_bar_open_time",
    "is_ideal_entry",
)


def build_detector_feature_manifest() -> dict[str, object]:
    return {
        "feature_columns": list(DETECTOR_FEATURE_COLUMNS),
        "feature_count": len(DETECTOR_FEATURE_COLUMNS),
        "identity_columns": list(DETECTOR_IDENTITY_COLUMNS),
        "blocked_columns": list(BLOCKED_COLUMNS),
    }


def build_gate_feature_manifest() -> dict[str, object]:
    return {
        "feature_columns": list(GATE_FEATURE_COLUMNS),
        "feature_count": len(GATE_FEATURE_COLUMNS),
        "numeric_feature_columns": list(GATE_NUMERIC_FEATURE_COLUMNS),
        "categorical_feature_columns": list(GATE_CATEGORICAL_FEATURE_COLUMNS),
        "identity_columns": list(GATE_IDENTITY_COLUMNS),
    }
